### PR TITLE
Update data_services to use notifications and guards rather than if s…

### PR DESCRIPTION
**Pull request by lwgordonimos**
…tatements

Additional to this incomplete fix: https://github.com/aodn/chef/pull/984.

Having resources defined in a ruby if block means they are not only not *run* but that they don't *exist*. This makes it really complicated when dealing with notifications/dependencies.

### CODE REVIEW

**Comment by jonescc** [comment]
+1 Fixes remaining issue for me.

**Comment by jonescc** [comment]
Still getting a file not writeable error:

```
vagrant@vagrant:~$ ls -al /var/incoming/SRS/OC/BODBAW/
total 8
drwxrwxr-x 2 pipeline_worker vagrant 4096 May 14 12:08 .
drwxr-xr-x 3 root            root    4096 May 14 10:09 ..
vagrant@vagrant:~$ cp /vagrant/src/IMOS_SRS-OC-BODBAW_X_20160902T231000Z_TSsep2016-absorption-CDOM_FV02_END-20160906T233000Z.nc /var/incoming/SRS/OC/BODBAW/
vagrant@vagrant:~$ ls -al /var/incoming/SRS/OC/BODBAW/
total 124
drwxrwxr-x 2 pipeline_worker vagrant   4096 May 14 12:59 .
drwxr-xr-x 3 root            root      4096 May 14 10:09 ..
-rwxrw-r-- 1 vagrant         vagrant 118480 May 14 12:59 IMOS_SRS-OC-BODBAW_X_20160902T231000Z_TSsep2016-absorption-CDOM_FV02_END-20160906T233000Z.nc
vagrant@vagrant:~$ tail -n 30 /mnt/ebs/log/pipeline/process/tasks.SRS_OC_BODBAW.log
2020-05-14 12:59:39,045 SYSINFO tasks.SRS_OC_BODBAW[b454816c-526b-4fc7-9278-bbc0ef547d7f] PipelineTask.error_exit_policies -> []
2020-05-14 12:59:39,045 SYSINFO tasks.SRS_OC_BODBAW[b454816c-526b-4fc7-9278-bbc0ef547d7f] IncomingFileStateManager.state -> 'FILE_IN_INCOMING'
2020-05-14 12:59:39,045 ERROR tasks.SRS_OC_BODBAW[b454816c-526b-4fc7-9278-bbc0ef547d7f] exception occurred initialising IncomingFileStateManager
Traceback (most recent call last):
  File "/vagrant/src/python-aodncore/aodncore/pipeline/watch.py", line 469, in _pre_processing_checks
    validate_file_writable(self.input_file)
  File "/vagrant/src/python-aodncore/aodncore/util/fileops.py", line 362, in validate_file_writable
    raise ValueError("file '{file}' is not writable".format(file=path))
ValueError: file '/var/incoming/SRS/OC/BODBAW/IMOS_SRS-OC-BODBAW_X_20160902T231000Z_TSsep2016-absorption-CDOM_FV02_END-20160906T233000Z.nc' is not writable
2020-05-14 12:59:39,050 ERROR tasks.SRS_OC_BODBAW[b454816c-526b-4fc7-9278-bbc0ef547d7f] unhandled exception in PipelineTask
Traceback (most recent call last):
  File "/vagrant/src/python-aodncore/aodncore/pipeline/watch.py", line 209, in run
    file_state_manager.move_to_processing()
  File "/mnt/ebs/pipeline/lib/python3.5/site-packages/transitions/core.py", line 405, in trigger
    return self.machine._process(func)
  File "/mnt/ebs/pipeline/lib/python3.5/site-packages/transitions/core.py", line 1073, in _process
    return trigger()
  File "/mnt/ebs/pipeline/lib/python3.5/site-packages/transitions/core.py", line 423, in _trigger
    return self._process(event_data)
  File "/mnt/ebs/pipeline/lib/python3.5/site-packages/transitions/core.py", line 433, in _process
    if trans.execute(event_data):
  File "/mnt/ebs/pipeline/lib/python3.5/site-packages/transitions/core.py", line 279, in execute
    machine.callback(func, event_data)
  File "/mnt/ebs/pipeline/lib/python3.5/site-packages/transitions/core.py", line 1031, in callback
    func(*event_data.args, **event_data.kwargs)
  File "/vagrant/src/python-aodncore/aodncore/pipeline/watch.py", line 469, in _pre_processing_checks
    validate_file_writable(self.input_file)
  File "/vagrant/src/python-aodncore/aodncore/util/fileops.py", line 362, in validate_file_writable
    raise ValueError("file '{file}' is not writable".format(file=path))
ValueError: file '/var/incoming/SRS/OC/BODBAW/IMOS_SRS-OC-BODBAW_X_20160902T231000Z_TSsep2016-absorption-CDOM_FV02_END-20160906T233000Z.nc' is not writable
vagrant@vagrant:~$ 
```

**Comment by lwgordonimos** [comment]
Sorry I should have mentioned. If it's your same running pipeline box, it needs to have supervisord restarted (or else the whole VM would do), in order for the running processes to pick up the group change.

**Comment by jonescc** [comment]
I destroyed the pipeline box and ran bin/pipeline-box.sh again and I still get an error:

```
==> pipeline: Chef Client finished, 189/338 resources updated in 1673.301487221 seconds
craigj@craigj-XPS-15-9550:/tmp/chef$ vagrant ssh pipeline
WARNING: No node hostname found, using name instead!!!
Welcome to Ubuntu 16.04.6 LTS (GNU/Linux 4.4.0-142-generic x86_64)

 * Documentation:  https://help.ubuntu.com
 * Management:     https://landscape.canonical.com
 * Support:        https://ubuntu.com/advantage
New release '18.04.4 LTS' available.
Run 'do-release-upgrade' to upgrade to it.

Australian Government, Department of Education

Access to this computer system is restricted to personnel of IMOS.  All
connections are logged.  Unauthorised access to this machine is prohibited,
disconnect NOW if you have not been expressly authorised to use the system.

Unauthorised use is a criminal offence under the Criminal Code Act 1995.
Last login: Tue May 28 13:24:51 2019 from 10.0.2.2
vagrant@vagrant:~$ cp /vagrant/src/IMOS_SRS-OC-BODBAW_X_
IMOS_SRS-OC-BODBAW_X_19850307T000000Z_SB8591-pigment_FV02_END-19910501T010000Z.nc             IMOS_SRS-OC-BODBAW_X_20160902T231000Z_TSsep2016-absorption-CDOM_FV02_END-20160906T233000Z.nc
vagrant@vagrant:~$ cp /vagrant/src/IMOS_SRS-OC-BODBAW_X_20160902T231000Z_TSsep2016-absorption-CDOM_FV02_END-20160906T233000Z.nc /var/incoming/SRS/OC/BODBAW/
vagrant@vagrant:~$ tail -n 30 /mnt/ebs/log/pipeline/process/tasks.SRS_OC_BODBAW.log
2020-05-14 14:23:10,557 SYSINFO tasks.SRS_OC_BODBAW[2bd9e003-7277-41b0-9868-d4e477f53244] PipelineTask.error_exit_policies -> []
2020-05-14 14:23:10,557 SYSINFO tasks.SRS_OC_BODBAW[2bd9e003-7277-41b0-9868-d4e477f53244] IncomingFileStateManager.state -> 'FILE_IN_INCOMING'
2020-05-14 14:23:10,557 ERROR tasks.SRS_OC_BODBAW[2bd9e003-7277-41b0-9868-d4e477f53244] exception occurred initialising IncomingFileStateManager
Traceback (most recent call last):
  File "/vagrant/src/python-aodncore/aodncore/pipeline/watch.py", line 469, in _pre_processing_checks
    validate_file_writable(self.input_file)
  File "/vagrant/src/python-aodncore/aodncore/util/fileops.py", line 362, in validate_file_writable
    raise ValueError("file '{file}' is not writable".format(file=path))
ValueError: file '/var/incoming/SRS/OC/BODBAW/IMOS_SRS-OC-BODBAW_X_20160902T231000Z_TSsep2016-absorption-CDOM_FV02_END-20160906T233000Z.nc' is not writable
2020-05-14 14:23:10,562 ERROR tasks.SRS_OC_BODBAW[2bd9e003-7277-41b0-9868-d4e477f53244] unhandled exception in PipelineTask
Traceback (most recent call last):
  File "/vagrant/src/python-aodncore/aodncore/pipeline/watch.py", line 209, in run
    file_state_manager.move_to_processing()
  File "/mnt/ebs/pipeline/lib/python3.5/site-packages/transitions/core.py", line 405, in trigger
    return self.machine._process(func)
  File "/mnt/ebs/pipeline/lib/python3.5/site-packages/transitions/core.py", line 1073, in _process
    return trigger()
  File "/mnt/ebs/pipeline/lib/python3.5/site-packages/transitions/core.py", line 423, in _trigger
    return self._process(event_data)
  File "/mnt/ebs/pipeline/lib/python3.5/site-packages/transitions/core.py", line 433, in _process
    if trans.execute(event_data):
  File "/mnt/ebs/pipeline/lib/python3.5/site-packages/transitions/core.py", line 279, in execute
    machine.callback(func, event_data)
  File "/mnt/ebs/pipeline/lib/python3.5/site-packages/transitions/core.py", line 1031, in callback
    func(*event_data.args, **event_data.kwargs)
  File "/vagrant/src/python-aodncore/aodncore/pipeline/watch.py", line 469, in _pre_processing_checks
    validate_file_writable(self.input_file)
  File "/vagrant/src/python-aodncore/aodncore/util/fileops.py", line 362, in validate_file_writable
    raise ValueError("file '{file}' is not writable".format(file=path))
ValueError: file '/var/incoming/SRS/OC/BODBAW/IMOS_SRS-OC-BODBAW_X_20160902T231000Z_TSsep2016-absorption-CDOM_FV02_END-20160906T233000Z.nc' is not writable
vagrant@vagrant:~$ ls -al /var/incoming/SRS/OC/BODBAW
total 124
drwxrwxr-x 2 vagrant vagrant   4096 May 14 14:23 .
drwxr-xr-x 3 root    root      4096 May 14 14:19 ..
-rwxrw-r-- 1 vagrant vagrant 118480 May 14 14:23 IMOS_SRS-OC-BODBAW_X_20160902T231000Z_TSsep2016-absorption-CDOM_FV02_END-20160906T233000Z.nc
vagrant@vagrant:~$ 
```

**Comment by lwgordonimos** [comment]
Ok I think I see the problem. On a fresh deployment, it still starts supervisor *before* it gets to addng the user to the group. I'll add the dependency and test from scratch again.

**Comment by jonescc** [comment]
Looks good. Running up the pipeline box for the first time and I can now run the example harvester as expected.

**Comment by lwgordonimos** [comment]
Great. Hopefully when we tackle the Chef work we can refactor this slightly more to be a bit less fragile when changes are made in future, and have less variance between pipeline box and real servers.

**Comment by lbesnard** [comment]
can we merge this :) ? Running the pipeline box would enlight my day today

**Comment by jonescc** [comment]
IS theer some other testing required before merging this?  I've just been testing the pipeline box

**Comment by lwgordonimos** [comment]
Probably also need to test with a Vagrant deploy of a real node, before it heads to RC. I'm just running RC up now...

**Pull request merged**
