### PR TITLE
Update data_services to fix Python environment setup and dependency in…

### PR DESCRIPTION
**Pull request by lwgordonimos**
…stallation.

In a nutshell, poise-python is expecting to manage Python environments, and it gets very confusing and flaky if half of the Python setup comes from system packages and half from Poise python (particular with multiple language versions, virtual environments, pip being upgraded in-place, etc. etc.).

### CODE REVIEW

**Comment by lwgordonimos** [comment]
@lbesnard would you mind running up pipeline box from this branch, and see if it works for you?

**Comment by lbesnard** [comment]
it works !!!

**Comment by lbesnard** [comment]
@lwgordonimos so it looks like this is not working anymore.

I have now an issue with cftime
```
==> pipeline:   x86_64-linux-gnu-gcc: fatal error: no input files                                                                                                                             
==> pipeline:   compilation terminated.                                                                                                                                                       
==> pipeline:   error: command 'x86_64-linux-gnu-gcc' failed with exit status 1                                                                                                               
==> pipeline:                                                                                                                                                                                 
==> pipeline:   ----------------------------------------                                                                                                                                      
==> pipeline:   Running setup.py clean for cftime                                                                                                                                             
==> pipeline: Failed to build cftime        
```

my data-services repo is up to date with the new constraints.txt file. and so is this branch.

**Comment by anguss00** [comment]
Same issue as @lbesnard with cftime

**Comment by lwgordonimos** [comment]
@anguss00 @lbesnard updated to get rid of pipeline 1 code which we a) don't need and b) was the cause of the breakage.

Tested on both pipeline node and real nodes in Vagrant, so see how it looks now.

**Comment by lbesnard** [comment]
thanks @lwgordonimos , it works great

**Pull request merged**
