### PR TITLE
Pin netcdf4 to version 1.3.1

### PR DESCRIPTION
**Pull request by anguss00**
Workaround for https://github.com/ioos/compliance-checker/issues/579

### CODE REVIEW

**Comment by lwgordonimos** [comment]
Sorry, I was looking into this but ran out of time. This will do for now, but I think the root cause is this other workaround being too aggressive in updating dependencies: https://github.com/aodn/chef/blob/master/cookbooks/imos_po/recipes/pipeline.rb#L188

This hack will do for now, and we can look at whether we can revisit that resource above to make it behave. Maybe the latest poise fixed the issue we were having with python_package at the time?

**Comment by anguss00** [comment]
Yeah fair call @lwgordonimos that --upgrade flag is pretty aggro. I have a feeling that poise is doing things correctly now, as I was able to use the package resource here to downgrade the netcdf4 version

**Comment by anguss00** [comment]
I quickly dashed this through as it was affecting prod

**Comment by lwgordonimos** [comment]
No probs, I don't have a problem with it as an urgent fix ;)

The behaviour we want is "manage the target package according to version requirement, only update dependencies if the target package updates requirements". That's the only way to prevent untested changes flying out of PyPI into production!

**Comment by anguss00** [comment]
Yesss it's a timebomb waiting to explode at the mo

**Comment by mhidas** [comment]
:+1: Thanks guys.

**Pull request merged**
