### PR TITLE
Add latest postgres driver to bundled maven repo for talend 7

### PR DESCRIPTION
**Pull request by jonescc**
Allows talend harvesters using latest driver to be built by jenkins

### CODE REVIEW

**Comment by jonescc** [comment]
@lwgordonimos - needs 13-aws-syd to be provisioned.  How do I do that?

**Comment by lwgordonimos** [comment]
@jonescc sorry, trying to get it cooked, but it's having a weird issue with timing out trying to set the timezone... will see if I can get to the bottom of that and finish the cook.

**Comment by jonescc** [comment]
No worries.  Thought you might have forgotten so a reminder only.   I think Loz is trying to get this one tidied up before going on holiday.   He's hoping to try it out on Monday.

**Comment by lwgordonimos** [comment]
Ok, cooked now.

**Pull request merged**
