### PR TITLE
Compliance checker/pip requirements update

### PR DESCRIPTION
**Pull request by lwgordonimos**
This is to enable the upgrade of the compliance-checker package.

1. lifts netCDF4 constraints due to conflicting with compliance-checker 4.1.1
1. ensures the 'libudunits2-dev' package is installed prior to installing Python requirements since it is a requirement for cfunits
1. includes/supersedes https://github.com/aodn/chef/pull/740

### CODE REVIEW

**Comment by lwgordonimos** [comment]
@mhidas @bpasquer I've tested this in my PO box and it looks OK. Might be good if someone else tests in PO before we push to RC?

**Comment by mhidas** [comment]
I'll give it a go.

**Comment by mhidas** [comment]
Seems to work fine for me.

**Comment by mhidas** [comment]
However I did have to do this first:  https://github.com/aodn/chef/pull/743

**Pull request merged**
