### PR TITLE
Added sysadmin email cc config

### PR DESCRIPTION
**Pull request by bhasin85**
[Portal PR](https://github.com/aodn/aodn-portal/pull/2331)
[Chef PR](https://github.com/aodn/chef/pull/397)
[Chef-Private PR](https://github.com/aodn/chef-private/pull/2079)

### CODE REVIEW

**Comment by julian1** [comment]
Did we want to use bcc?

**Comment by bhasin85** [comment]
@julian1  I think we agreed to go with cc during the planning meeting.

**Comment by lwgordonimos** [comment]
@bhasin85 I think we did decide on CC but I don't believe it was in terms of the sys.admin list... this would put the sys.admin email address in the CC back to the end user, and we don't want users using that as a return address... whatever it is, it should be something that we don't mind end users emailing us on.

**Comment by bhasin85** [comment]
@pblain  What do you think about it?

**Options**

1. cc sys.admin@emii.org.au 
2. bcc sys.admin@emii.org.au
3. cc someOtherEmailAddress@emii.org.au

**Comment by pblain** [comment]
Easiest to switch it to a BCC - there's no real need for the user to see it.

**Pull request merged**
