### PR TITLE
Set CF_STANDARD_NAME_TABLE environment variable in global profile for…

### PR DESCRIPTION
**Pull request by lwgordonimos**
… pipeline hosts

### CODE REVIEW

**Comment by mhidas** [comment]
:+1:

**Comment by mhidas** [comment]
Should this change be on RC now? I it doesn't seem to be.

**Comment by lwgordonimos** [comment]
Works for me?

```
4-nec-hob:~$ echo $CF_STANDARD_NAME_TABLE 
/mnt/ebs/aodn-pipeline/etc/cf-standard-name-table.xml
```

**Comment by ccmoloney** [comment]
Also works for me

**Pull request merged**
