### PR TITLE
Add support for configuring the wps file expiry time

### PR DESCRIPTION
**Pull request by anguss00**

### CODE REVIEW

**Comment by lwgordonimos** [comment]
@anguss00 this will also need to be changed in https://github.com/aodn/chef-private/blob/master/aws/ebprep/conf/templates/aodn-portal/Portal.groovy.template

**Comment by anguss00** [comment]
Good point!

**Comment by anguss00** [comment]
Just putting up the chef-private PR now

**Comment by julian1** [comment]
Why is this in Portal config rather than geoserver config?

**Comment by anguss00** [comment]
@julian1 only because of the email footer content that's sent out after a ggd job is initiated. It's just to configure how long the expiry time is in that email.

**Pull request merged**
