### PR TITLE
imos_po: Bulk async upload option

### PR DESCRIPTION
**Pull request by danfruehauf**
Upload many files asynchronously by piping them to
`async-upload.py`.

Example usage for a single file:
```
$ echo "SRC DST" | async-upload.py
$ echo "/tmp/IMOS_ACORN_V_20100716T060000Z_BONC_FV00_sea-state.n IMOS/ACORN/vector/BONC/2010/07/16/IMOS_ACORN_V_20100716T060000Z_BONC_FV00_sea-state.nc" | async-upload.py
```

Uploading multiple files:
```
$ find . -type f | cut -c3- | awk -v pwd=$PWD '{print pwd"/"$1 " " "IMOS/"$1}'
/tmp/ABOS_SOFS/ff/d/e/file2 IMOS/d/e/file2
/tmp/ABOS_SOFS/ff/file3 IMOS/file3
/tmp/ABOS_SOFS/ff/a/b/c/file1 IMOS/a/b/c/file1

$ find . -type f | cut -c3- | awk -v pwd=$PWD '{print pwd"/"$1 " " "IMOS/"$1}' | async-upload.py
```

### CODE REVIEW

**Comment by danfruehauf** [comment]
@lbesnard Would be very useful for uploading whole AUV campaigns.

@mhidas Would be useful for uploading large amounts of data such as passive acoustics.

This will work on the PO box as expected - moving files to `/s3/imos-data`

**Comment by danfruehauf** [comment]
I forgot to mention that this is the technique I used to upload the SRS data - and that was quick. By default, it'll use up to 4 concurrent threads to upload the data and the queuing of the files should be super quick and bound only by the time it takes `find` to iterate on the filesystem.

**Comment by mhidas** [comment]
Obviously this is upload without indexing, right?

**Comment by danfruehauf** [comment]
> Obviously this is upload without indexing, right?

Yes. It is supposed to assist with bulk uploading in the future. It's a "power user" feature.

**Pull request merged**
