### PR TITLE
imos_po: s3lsv - List versions of file on S3

### PR DESCRIPTION
**Pull request by danfruehauf**
Explore previous versions of objects using `s3lsv`.

Basic usage:
```
$ s3lsv
usage: s3-lsv.py [-h] [-a] -b BUCKET -k KEY [-o OUTPUT] [-v VERSION]
s3-lsv.py: error: argument -b/--bucket is required

$ s3lsv -a -b imos-data -k IMOS/
IMOS/AATAMS/
IMOS/ABOS/
...
IMOS/SRS/

$ s3lsv -a -b imos-data -k IMOS/ACORN/radial/TAN/2016/01/01/IMOS_ACORN_RV_20160101T235000Z_TAN_FV00_radial.nc
na5gI3LrPUyyfZ3JsHDFDV3WTAmFt2n5 2016-01-01T23:55:13.000Z IMOS/ACORN/radial/TAN/2016/01/01/IMOS_ACORN_RV_20160101T235000Z_TAN_FV00_radial.nc

$ s3lsv -a -b imos-data -k IMOS/ACORN/radial/TAN/2016/01/01/IMOS_ACORN_RV_20160101T235000Z_TAN_FV00_radial.nc -o /tmp/file.nc -v na5gI3LrPUyyfZ3JsHDFDV3WTAmFt2n5
$ ls -l /tmp/file.nc
-rw-rw-r-- 1 vagrant vagrant 263728 Jan  2 10:55 /tmp/file.nc
```

### CODE REVIEW

**Comment by danfruehauf** [comment]
@mhidas @lbesnard @ggalibert @pblain @bpasquer @xhoenner FYI

If anyone can come up with a better name than `s3lsv` - please suggest it. I chose s3lsv because it's like s3ls, but with version support.

Perhaps it is something I should try and contribute upstream to `s3cmd`.

**Comment by mhidas** [comment]
@danfruehauf Will the output indicate which is the *current* version?

**Comment by danfruehauf** [comment]
@mhidas That should give it to you:
```
$ s3lsv -a -b BUCKET -k KEY | sort -k2 | tail -1
```

That'll sort it by date.

**Comment by mhidas** [comment]
Could we make it so the output is always sorted by date? Or rather by key, then date, if `KEY` can match multiple objects. I think that makes sense.

**Comment by danfruehauf** [comment]
> Could we make it so the output is always sorted by date? Or rather by key, then date, if KEY can match multiple objects. I think that makes sense.

Could do. Latest is last or first?

**Comment by danfruehauf** [comment]
> Could do. Latest is last or first?

@mhidas Looks like it'll sort it by default. Latest is first.

**Comment by mhidas** [comment]
:+1:

**Comment by danfruehauf** [comment]
Feel free to merge it then. It's a utility that will be installed on 10-aws-syd. It will not really be usable on the po box.

**Pull request merged**
