### PR TITLE
Deploy event-driven ABOS pipelines

### PR DESCRIPTION
**Pull request by mhidas**
* rename abos_sofs_surface_properties to abos_sofs_sp (to match schema name)
* rename abos_ts_single_inst_timeseries to abos_ts (to match schema name)
* (abos_sots already done)

### CODE REVIEW

**Comment by mhidas** [comment]
@danfruehauf FYI

**Comment by danfruehauf** [comment]
Thanks, I'll get aodn/chef-private#1767 up to date.

**Comment by danfruehauf** [comment]
@mhidas Add them also to nodes/po.json (please keep them sorted).

**Comment by mhidas** [comment]
@danfruehauf Ah, yes, I forgot about that. Done.

**Comment by danfruehauf** [comment]
:+1:

**Comment by mhidas** [comment]
Just rebased and added a missing regex pattern.

**Comment by danfruehauf** [comment]
> Just rebased and added a missing regex pattern.

Did the required work on aodn/chef-private. No worries.

**Pull request merged**
