### PR TITLE
Bump mixlib-shellout version

### PR DESCRIPTION
**Pull request by lwgordonimos**
@lbesnard Try this change locally before merging. 

The issue looks to be that they have 'yanked' the version from RubyGems:
https://rubygems.org/gems/mixlib-shellout/versions/1.6.0

### CODE REVIEW

**Comment by lbesnard** [comment]
so far so good !

**Comment by lwgordonimos** [comment]
@lbesnard Bumping JSON version as well. Bundle install now works again for me, can you give it a go as well?

https://github.com/flori/json/issues/229

**Comment by lbesnard** [comment]
I only have another issue with  ffi-yajl

```bash
bundle install >

Using treetop 1.5.3
Using rspec 2.99.0
Gem::Ext::BuildError: ERROR: Failed to build gem native extension.

    current directory: /tmp/bundler20160913-21201-a3u00gffi-yajl-1.1.0/gems/ffi-yajl-1.1.0/ext/ffi_yajl/ext/encoder
/usr/bin/ruby2.3 -r ./siteconf20160913-21201-1kdqmm0.rb extconf.rb
*** extconf.rb failed ***
Could not create Makefile due to some reason, probably lack of necessary
libraries and/or headers.  Check the mkmf.log file for more details.  You may
need configuration options.

Provided configuration options:
        --with-opt-dir
        --without-opt-dir
        --with-opt-include
        --without-opt-include=${opt-dir}/include
        --with-opt-lib
        --without-opt-lib=${opt-dir}/lib
        --with-make-prog
        --without-make-prog
        --srcdir=.
        --curdir
        --ruby=/usr/bin/$(RUBY_BASE_NAME)2.3
extconf.rb:8:in `<main>': undefined method `include_path' for Libyajl2:Module (NoMethodError)
Did you mean?  include

extconf failed, exit code 1

Gem files will remain installed in /tmp/bundler20160913-21201-a3u00gffi-yajl-1.1.0/gems/ffi-yajl-1.1.0 for inspection.
Results logged to
/tmp/bundler20160913-21201-a3u00gffi-yajl-1.1.0/extensions/x86_64-linux/2.3.0/ffi-yajl-1.1.0/gem_make.out

An error occurred while installing ffi-yajl (1.1.0), and Bundler cannot continue.
Make sure that `gem install ffi-yajl -v '1.1.0'` succeeds before bundling.
```

then 
```bash
lbesnard ~/github_repo/chef $ sudo gem install ffi-yajl -v '1.1.0'                                                    
Building native extensions.  This could take a while...
ERROR:  Error installing ffi-yajl:
        ERROR: Failed to build gem native extension.

    current directory: /var/lib/gems/2.3.0/gems/ffi-yajl-1.1.0/ext/ffi_yajl/ext/encoder
/usr/bin/ruby2.3 -r ./siteconf20160913-21483-17zd06k.rb extconf.rb
*** extconf.rb failed ***
Could not create Makefile due to some reason, probably lack of necessary
libraries and/or headers.  Check the mkmf.log file for more details.  You may
need configuration options.

Provided configuration options:
        --with-opt-dir
        --without-opt-dir
        --with-opt-include
        --without-opt-include=${opt-dir}/include
        --with-opt-lib
        --without-opt-lib=${opt-dir}/lib
        --with-make-prog
        --without-make-prog
        --srcdir=.
        --curdir
        --ruby=/usr/bin/$(RUBY_BASE_NAME)2.3
extconf.rb:8:in `<main>': undefined method `include_path' for Libyajl2:Module (NoMethodError)
Did you mean?  include

extconf failed, exit code 1

Gem files will remain installed in /var/lib/gems/2.3.0/gems/ffi-yajl-1.1.0 for inspection.
Results logged to /var/lib/gems/2.3.0/extensions/x86_64-linux/2.3.0/ffi-yajl-1.1.0/gem_make.out
```

**Comment by bhasin85** [comment]
@lwgordonimos @lbesnard Can we close/merge this PR?

**Pull request closed without merging**
