### PR TITLE
create new schema for NRMN

### PR DESCRIPTION
**Pull request by ana-berger**
Please, could you check if that is correct for creating a new schema?

### CODE REVIEW

**Review by mhidas — APPROVED** [review]
Looks fine to me.
However, I'm not sure this is actually going to have any effect. Config in the chef repo is only used in the pipeline box, but even that box uses the database in the stack (configured elsewhere!). So I don't think there's any point adding these schemas in chef anymore. 

Correct me if I'm wrong @lwgordonimos

**Comment by mhidas** [comment]
@lwgordonimos Are we ready to start adding this sort of config in data-services instead??

**Comment by mhidas** [comment]
@ana-berger For RC & prod, you'll need to put the config in chef-private (see https://github.com/aodn/chef-private/pull/3583 for example)
For the po stack, the same config goes in the [cloud-deploy](https://github.com/aodn/cloud-deploy/tree/master/sample-config/data_bags) repo, I think.

**Comment by ana-berger** [comment]
@mhidas yes I knew I need to add config in chef-private as well. Going through it right now.

**Comment by ana-berger** [comment]
> For the po stack, the same config goes in the [cloud-deploy](https://github.com/aodn/cloud-deploy/tree/master/sample-config/data_bags) repo, I think.
So, for the stack to have the schema we need to add it in cloud-deploy? Is that ok if I send a PR then to do that or is it something for the devs? @lwgordonimos

**Comment by lwgordonimos** [comment]
> Are we ready to start adding this sort of config in data-services instead??
Not yet unfortunately, there were questions to be answered around database credentials first.

> Is that ok if I send a PR then to do that or is it something for the devs?

Just for completeness, the best thing until we sort this mess out a bit is to add it here as you need it, and I'll just replicate it over to cloud-deploy. Sorry it's pretty annoying, but kind of in a transitional phase...

**Comment by ana-berger** [comment]
All good @lwgordonimos, I got it. Thank you for the clarification!

**Pull request merged**
