### PR TITLE
Removed pnp4nagios from Nagios

### PR DESCRIPTION
**Pull request by pmbohm**
Requires https://github.com/aodn/chef-private/pull/2298
This pull request also contains changes to allow Nagios to run on Xenial, therefore testing can be done in Vagrant (8-aws-syd)

### CODE REVIEW

**Comment by pmbohm** [comment]
@julian1  Did you look at this as a whole to merge into master?

**Comment by julian1** [comment]
@pblain I've never seen this before in my life!

**Comment by pblain** [comment]
@julian1 - any ideas how it got merged?

**Comment by pmbohm** [comment]
The hilarity, fun and games can continue in seperate pull request now.

**Comment by julian1** [comment]
@pblain I merged another pull-request for the perceived up-time monitor, https://github.com/aodn/chef/pull/506 that I believed was intended for production. I failed to notice that PR was only created against this branch. It was my mistake, and @pmbohm was not around to point out the error.

**Comment by julian1** [comment]
I had some comments in https://github.com/aodn/chef/pull/506, that would probably be good to address too. It was probably a mistake for me to merge. But there was a sense of urgency given it was the end of iteration, and I thought the task was substantially complete.

**Pull request closed without merging**
